In [3]:
import pandas as pd

In [5]:
A = pd.read_json('./assets/data/'+'cases_world.json')

In [8]:
A[A.country == 'Italy']

,location,time,cases,deaths,hospitalized,ICU,recovered,longitude,latitude,deaths-GR,cases-GR,country
3555,Full Country,2019-12-31,0.0,0.0,NaN,NaN,NaN,12.674297,42.638426,0.000000,0.000000,Italy
3556,Full Country,2020-01-01,0.0,0.0,NaN,NaN,NaN,12.674297,42.638426,0.000000,0.000000,Italy
3557,Full Country,2020-01-02,0.0,0.0,NaN,NaN,NaN,12.674297,42.638426,0.000000,0.000000,Italy
3558,Full Country,2020-01-03,0.0,0.0,NaN,NaN,NaN,12.674297,42.638426,0.000000,0.000000,Italy
3559,Full Country,2020-01-04,0.0,0.0,NaN,NaN,NaN,12.674297,42.638426,0.000000,0.000000,Italy
...,...,...,...,...,...,...,...,...,...,...,...,...
10745,Valle d'Aosta,2020-03-25T17:00:00,401.0,24.0,70.0,25.0,2.0,7.387426,45.730099,0.208247,0.002494,Italy
10746,Valle d'Aosta,2020-03-26T17:00:00,408.0,28.0,73.0,24.0,2.0,7.387426,45.730099,0.142806,0.017156,Italy
10747,Valle d'Aosta,2020-03-27T17:00:00,452.0,37.0,91.0,24.0,2.0,7.387426,45.730099,0.243178,0.097343,Italy
10748,Valle d'Aosta,2020-03-28T17:00:00,511.0,41.0,90.0,26.0,2.0,7.387426,45.730099,0.097537,0.115458,Italy
10749,Valle d'Aosta,2020-03-29T17:00:00,584.0,43.0,90.0,26.0,2.0,7.387426,45.730099,0.046501,0.124998,Italy

In [19]:
A[A.country == 'Italy']['time'].iloc[-2][:10] == A[(A.country == 'Italy')&(A.location == 'Full Country')]['time'].iloc[-1][:10][:10]

True

In [57]:
A['C'] = A.location+A.country
list_of_lastupdates = [A[A['C'] == C]['time'].tail(1).values[0][:10] for C in A['C'].unique()]

In [61]:
A.loc[A.groupby(['country']).time.idxmax()]

ValueError:

In [74]:
A['time'] = A['time'].str.slice(0,10)
A.sort_values('time')[0]
A.sort_values('time').groupby(['country','location']).tail(1)

,location,time,cases,deaths,hospitalized,ICU,recovered,longitude,latitude,deaths-GR,cases-GR,country,C
10795,Auvergne RhÃ´ne-Alpes,2020-02-20,6.0,0.0,6.0,NaN,NaN,4.660481,45.296812,NaN,NaN,France,Auvergne RhÃ´ne-AlpesFrance
7463,Qinghai,2020-02-23,18.0,0.0,NaN,NaN,18.0,95.952116,35.407095,0.000000,0.000000,China,QinghaiChina
7326,Xizang,2020-02-23,1.0,0.0,NaN,NaN,1.0,87.078137,31.894343,NaN,NaN,China,XizangChina
8002,Anhui,2020-03-08,990.0,6.0,NaN,NaN,984.0,117.000000,32.000000,0.000000,0.000000,China,AnhuiChina
7508,Xinjiang,2020-03-08,76.0,3.0,NaN,NaN,73.0,87.167384,41.757477,0.000000,0.000000,China,XinjiangChina
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10469,Friuli Venezia Giulia,2020-03-29,1480.0,98.0,236.0,60.0,241.0,13.055904,46.151042,0.112233,0.029730,Italy,Friuli Venezia GiuliaItaly
10504,Piemonte,2020-03-29,8206.0,684.0,2985.0,443.0,254.0,7.923549,45.060735,0.097952,0.065196,Italy,PiemonteItaly
10539,Puglia,2020-03-29,1549.0,86.0,559.0,99.0,31.0,16.621003,40.984254,0.174398,0.058747,Italy,PugliaItaly
7576,Beijing,2020-03-29,577.0,8.0,NaN,NaN,412.0,116.391276,39.906217,0.000000,0.006932,China,BeijingChina
11503,Nordrhein-Westfalen,2020-03-29,11400.0,98.0,NaN,NaN,NaN,7.554234,51.478180,0.183655,0.069561,Germany,Nordrhein-WestfalenGermany

In [81]:
A.sort_values('time').tail(1)['time'].values[0]

'2020-03-29'